### ISSUE TITLE
[Bug] If you start lines with "—" an extra empty line is added

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1409] opened 2024-01-29 09:43 UTC
Android, 2.4.15

1. Open Composer 
2. Type several lines (separated with Enter) starting with a long dash. For example: 
— Abcde
— Fghy
— Xyz
3. Clcik Send
4. An extra empty line is added between the lines 

https://github.com/linagora/twake-on-matrix/assets/97684890/0a500b1c-c216-4c98-ab1e-2206ac764939

**Comment by tprudentova** [comment] 2024-01-30 09:49
Same for lines starting with numbers


https://github.com/linagora/twake-on-matrix/assets/97684890/1d0c8fe1-0818-49c5-8267-3d3ad929d879

**Comment by hoangdat** [comment] 2024-01-30 10:32
Test: reproduced in Russian, not in Vietnam and Englisht

**Comment by hieutbui** [comment] 2024-03-19 07:55
@tprudentova Can you give me more information about:
- Keyboard name.
- Keyboard settings.
- Phone language settings.
From my side, can not reproduce it:

https://github.com/linagora/twake-on-matrix/assets/80142234/bf35b20c-0f87-4c2b-8345-1a429e72e28b

**Comment by Te-Z** [comment] 2024-07-05 14:34
closing this since we can't reproduce it

**Closed by Te-Z** 2024-07-05 14:34 UTC
Labels: bug, FT::COMPOSER
