### ISSUE TITLE
[IOS] Improve download handling When downloading file

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#1860] opened 2024-06-07 03:23 UTC
Related to: https://github.com/linagora/twake-on-matrix/pull/1814

On iOS the error is handled in 1/3 cases.

https://github.com/linagora/twake-on-matrix/assets/43041967/2c249b76-a6e9-4c0b-9561-ba7a20653efe

**Comment by nqhhdev** [comment] 2024-06-07 04:39
- Pls write more details for this case

**Comment by sherlockvn** [comment] 2024-06-18 07:48
@Te-Z

**Comment by Te-Z** [comment] 2024-07-01 15:31
Close this one since it's a duplicate of https://github.com/linagora/twake-on-matrix/issues/1702 and it's not only on iOS

**Closed by Te-Z** 2024-07-01 15:31 UTC
