### ISSUE TITLE
Send .HEIC, .HEIF across the platform

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#1577] opened 2024-03-12 10:40 UTC
### Desc: 
- Right now, Android versions below 10 can't open .HEIC files. We need a solution to show these images on older Androids. One idea is to change .HEIC images into png or jpeg format, which these devices can display. Also, use benchmark function to see it have a good performance
- If the file is sent from web or android, we don't need to convert it, just keep it as an unknown file

- Because the file may lose the quality of image and video, so we should ask designer and BA about this to improve UX @hoangdat 

### Reference:
https://pub.dev/packages/flutter_image_compress
https://pub.dev/packages/video_compress
### DOD:
- [ ] convert HEIC to JPG or PNG
- [ ] convert HEIF to MP4 or MOV

**Comment by hoangdat** [comment] 2024-03-15 03:17
what happen if convert failed

**Comment by sherlockvn** [comment] 2024-03-15 09:20
- take care on the process of convert, the UI/UX in case the file is too large

**Comment by sherlockvn** [comment] 2024-03-19 02:04
another idea is keep .HEIC, .HEIF display as a image, video in ios platform, and as a file in unsupported platform

**Comment by Te-Z** [comment] 2024-07-26 09:31
Duplicate of https://github.com/linagora/twake-on-matrix/issues/1980

**Closed by Te-Z** 2024-07-26 09:31 UTC
Labels: WEB, MOBILE, FT::Preview
