### ISSUE TITLE
Sometimes clicking on a notification freezes the screen on the conversation list

### ISSUE THREAD

**Issue by guimard** [linagora/twake-on-matrix#1864] opened 2024-06-10 02:29 UTC
Platform: Android 12
Version: 2.5.8

When receiving a notification, often but not always, the Twake screen freezes on conversation list. I have to kill application and restart it to see message content

**Comment by hoangdat** [comment] 2024-06-10 04:13
iOS also have the same problem: sometimes (20%)

**Comment by guimard** [comment] 2024-07-04 11:19
It seems that this happen when Twake-app is open and display the same chat than the one given in notification : then app switch back to the chat menu and blocks here

**Comment by Te-Z** [comment] 2024-07-05 09:13
Should be solved in 2.5.9 https://github.com/linagora/twake-on-matrix/pull/1867 
Need to test again

**Comment by guimard** [comment] 2024-07-05 15:17
> Should be solved in 2.5.9 #1867 Need to test again

Which version ?

**Comment by guimard** [comment] 2024-07-05 15:18
> Should be solved in 2.5.9 #1867 Need to test again

How can I get this version ?

**Comment by Te-Z** [comment] 2024-07-09 09:53
Reproduced 20% of the time on android: when it happens I was not able to enter any chat at all. Need to kill the app and restart it to fix it

**Comment by KhaledNjim** [comment] 2024-09-10 16:04
this seems to be fixed on newer version, reproduced on 2.5.8 

[2.5.8.webm](https://github.com/user-attachments/assets/774b8867-4503-4ef7-b881-61fd7cf6e83f)

but trying the same steps on 2.6.2 ( the version available on the play store) its working well

[2.6.2.webm](https://github.com/user-attachments/assets/9fa37713-4788-4ce7-be37-5ed1dc4dd2d0)

**Comment by nqhhdev** [comment] 2024-09-16 07:25
I fixed on PR: #1867 

This issue related to #1587

**Closed** 2024-09-27 07:51 UTC
Labels: bug, FT::NOTIFICATION
